### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by bradt** [aprea/wp-advanced-excerpt#26]
- [x] Ensure settings from 4.1.1 are correctly migrated to 4.2  
  _We've probably been testing mostly with 4.2 data all this time, so probably a good idea to test the transformation of the settings._
  - [x] Make sure that none of the behaviour changes for people who already have the plugin setup on their site
- [x] Version number updated in main plugin file
- [x] Update README.txt
  - [x] Version numbers
  - [x] Changelog
- [x] Do a testing run through just before release  
  _Always a good idea. Issues are often picked up last minute._
- [x] Push code and assets to WP.org
